site_name: UncertaintyModeler
site_description: Sklearn wrapper for classifications system that computes the prediction uncertainty
site_author: Jordi Allué


theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Advanced: advanced.md
  - About:
    - Release Notes: about/changelog.md
    - Contributing: about/contributing.md
    - License: about/license.md
